# Generated by Django 4.2 on 2024-09-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapping',
            name='short_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
