# Generated by Django 4.2 on 2024-09-04 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirection', '0002_alter_urlmapping_short_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlmapping',
            old_name='short_code',
            new_name='short_url',
        ),
    ]
