# Generated by Django 4.2 on 2024-09-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirection', '0003_rename_short_code_urlmapping_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapping',
            name='short_url',
            field=models.URLField(unique=True),
        ),
    ]
