# Generated by Django 4.2 on 2024-09-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirection', '0007_alter_urlmapping_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapping',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
    ]
