# Generated by Django 4.2 on 2024-09-04 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirection', '0010_alter_urlmapping_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlmapping',
            old_name='short_url',
            new_name='short_code',
        ),
        migrations.AlterField(
            model_name='urlmapping',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 20, 7, 56, 139489)),
        ),
    ]
