# Generated by Django 4.2 on 2024-09-04 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirection', '0013_alter_urlmapping_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapping',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 4, 12, 53, 14, 640096, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='urlmapping',
            name='original_url',
            field=models.URLField(max_length=2048),
        ),
    ]
