FROM python:3.9.19-slim-bullseye

RUN apt-get update && \
    apt-get install -y --no-install-recommends tzdata procps && \
    apt-get clean && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/*

ENV TZ Asia/Taipei

WORKDIR /app
COPY requirements.txt /app/
RUN pip install --upgrade pip
RUN pip3 install -r requirements.txt

COPY . /app

RUN python manage.py makemigrations && \
    python manage.py migrate

EXPOSE 8000

CMD gunicorn -c gunicorn.conf.py url_system_proj.wsgi:application